#!/usr/bin/env python3
"""gen_config_parser_vectors.py — generate asm vector table from TSV.

Reads tests/func/network_conf_vectors.tsv, writes an asm source
file defining _cp_vectors[] — a null-terminated array of records
the asm test runner walks. Format mirrors the Python loader's
escape grammar at scripts/test_lint_network_conf.py: `\\n` →
newline, `\\r` → CR; no other escapes.

Per-vector record layout (32 bytes, fixed for stride indexing):
  +0   name pointer        (.quad, 8 bytes)
  +8   expected             (.word, 4 bytes; 0=PASS, 1=FAIL)
 +12   code                 (.word, 4 bytes; 0=NONE, 1..8 per E_*)
 +16   input pointer        (.quad, 8 bytes)
 +24   input length         (.word, 4 bytes; in bytes)
 +28   pad                  (.word, 4 bytes)

Sentinel record: name pointer = 0.

The error-code naming and numeric mapping must stay byte-identical
to lib/config_parser.S's E_* constants. If those change, this map
changes too, and so does the runner's expectation logic.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

CODE_MAP: dict[str, int] = {
    "NONE": 0,
    "E_MAGIC": 1,
    "E_LINE": 2,
    "E_KEY": 3,
    "E_DUP": 4,
    "E_REQ": 5,
    "E_IP": 6,
    "E_HOST": 7,
    "E_MAC": 8,
}


def _expand_escapes(s: str) -> bytes:
    return s.replace("\\n", "\n").replace("\\r", "\r").encode("utf-8")


def _emit_bytes(name: str, blob: bytes) -> list[str]:
    """Emit `.byte` directives, 16 per line for readability."""
    out = [f"{name}:"]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        out.append("    .byte " + ", ".join(f"0x{b:02x}" for b in chunk))
    return out


def _gen(tsv_path: Path) -> str:
    rows: list[dict[str, object]] = []
    with tsv_path.open(encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for raw in reader:
            code_str = raw["code"]
            if code_str not in CODE_MAP:
                # Unknown code — list known options so the operator
                # can spot a typo immediately rather than chasing a
                # bare KeyError.
                row_name = raw["name"]
                known = ", ".join(sorted(CODE_MAP))
                raise ValueError(
                    f"vector {row_name!r} has unknown code "
                    f"{code_str!r}; expected one of: {known}"
                )
            rows.append({
                "name": raw["name"],
                "expected": 0 if raw["expected"] == "PASS" else 1,
                "code": CODE_MAP[code_str],
                "input": _expand_escapes(raw["input"]),
            })

    lines: list[str] = [
        "/* Auto-generated by scripts/gen_config_parser_vectors.py",
        " * from tests/func/network_conf_vectors.tsv.",
        " * DO NOT EDIT — regenerate via the Makefile rule. */",
        "",
        ".section .rodata",
        ".global _cp_vectors",
        "",
        ".balign 8",
        "_cp_vectors:",
    ]
    for i, row in enumerate(rows):
        # Bind dict accesses to locals so the f-strings below stay
        # double-quoted throughout (pylint W1405 inconsistent-quotes).
        expected = row["expected"]
        code = row["code"]
        inp = row["input"]
        assert isinstance(inp, bytes)
        lines.append(f"    .quad _cp_vec_{i}_name")
        lines.append(f"    .word {expected}")
        lines.append(f"    .word {code}")
        lines.append(f"    .quad _cp_vec_{i}_input")
        lines.append(f"    .word {len(inp)}")
        lines.append("    .word 0")
    # Sentinel.
    lines.extend([
        "    .quad 0",
        "    .word 0",
        "    .word 0",
        "    .quad 0",
        "    .word 0",
        "    .word 0",
        "",
    ])
    for i, row in enumerate(rows):
        name = row["name"]
        inp = row["input"]
        assert isinstance(inp, bytes)
        lines.append(f"_cp_vec_{i}_name:")
        lines.append(f'    .asciz "{name}"')
        lines.extend(_emit_bytes(f"_cp_vec_{i}_input", inp))
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(__doc__ or "").split("\n", maxsplit=1)[0],
    )
    ap.add_argument("tsv", type=Path,
                    help="input TSV at tests/func/network_conf_vectors.tsv")
    ap.add_argument("output", type=Path, help="output asm file")
    args = ap.parse_args()
    try:
        text = _gen(args.tsv)
    except OSError as e:
        print(f"gen_config_parser_vectors: {e}", file=sys.stderr)
        return 1
    args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
